import {
  Bird,
  Bug,
  Cat,
  Cloud,
  Dog,
  Droplet,
  Fish,
  Flame,
  Ghost,
  Heart,
  Leaf,
  Moon,
  Rabbit,
  Rocket,
  Snowflake,
  Squirrel,
  Star,
  Sun,
  Turtle,
  Zap,
} from 'lucide-react';
import type { ComponentType } from 'react';
import type { AvatarPreset } from '@pindrop/shared';

export const AVATAR_PRESET_ICONS: Record<AvatarPreset, ComponentType<{ className?: string }>> = {
  cat: Cat,
  dog: Dog,
  bird: Bird,
  fish: Fish,
  rabbit: Rabbit,
  squirrel: Squirrel,
  turtle: Turtle,
  bug: Bug,
  ghost: Ghost,
  rocket: Rocket,
  star: Star,
  heart: Heart,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  flame: Flame,
  droplet: Droplet,
  leaf: Leaf,
  snowflake: Snowflake,
};

export const AVATAR_PRESET_COLORS: Record<AvatarPreset, string> = {
  cat: 'bg-orange-500',
  dog: 'bg-amber-600',
  bird: 'bg-sky-500',
  fish: 'bg-blue-500',
  rabbit: 'bg-pink-400',
  squirrel: 'bg-amber-700',
  turtle: 'bg-emerald-600',
  bug: 'bg-lime-600',
  ghost: 'bg-slate-500',
  rocket: 'bg-indigo-500',
  star: 'bg-yellow-500',
  heart: 'bg-rose-500',
  zap: 'bg-amber-500',
  sun: 'bg-orange-400',
  moon: 'bg-violet-500',
  cloud: 'bg-cyan-500',
  flame: 'bg-red-500',
  droplet: 'bg-blue-400',
  leaf: 'bg-green-500',
  snowflake: 'bg-teal-500',
};
